[[pages]]
path = "MainPage.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Sign.py"
name = "Sign"
icon = "ğŸ "

[[pages]]
path = "pages/Simplificator.py"
name = "Simplificator"
icon = "ğŸ "

[[pages]]
path = "pages/Task.py"
name = "Task"
icon = "ğŸ "